# Generated by Django 3.2.6 on 2021-08-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('CPF', models.CharField(max_length=30)),
                ('Cirurgia', models.CharField(max_length=150)),
            ],
        ),
    ]
